source_dir: ./data/MELD.Raw
dataname: IEMOCAP 

data_dir: ./data/preprocessed/
target_dir: ./data/save/
model_name: Bert
bert_path: roberta-large
CLS: "<s>"
SEP: "</s>"
min_freq: 2

batch_size: 2
max_doc_length: 512
max_seq_length: 192
bert_lr: 2e-5
lr: 5e-4
beta1: 0.9
beta2: 0.84
patience: 10
max_grad_norm: 1.0
pair: use
loss_scale: 0
warmup_proportion: 0.1
gradient_accumulation_steps: 1
adam_epsilon: 1e-7
weight_decay: 1e-2
warmup_steps: 0
epoch_size: 20
dropout_rate: 0.2

spk_emb_dim: 300
lstm_hidden_size: 300
embedding_dim: 300
cnn_output_dim: 300
cnn_filters: 50
cnn_kernel_sizes: [3, 4, 5]
cnn_dropout: 0.5

text_in_size: 768
audio_in_size: 1582
video_in_size: 342

audio_out_size: 200
video_out_size: 200

text_hid_size: 200
audio_hid_size: 200
video_hid_size: 200

text_hidden_size: 300 
audio_hidden_size: 300 
video_hidden_size: 300 
align_size: 500

hidden_size: 300 
use_features: t,v,a
use_speaker: 0

speaker_emb_dim: 100

alpha: 10
temperature: 20

seed: 48
train_mode: random

cuda_index: 0
use_distill: 0
up_temp: 0.1
down_temp: 5

next_weight: 0.3
prev_weight: 0.0

margin: 0.1
label_weight: 1.3


grl_weight: 0.6
grl_loss: 0.7
cl_weight: 0.4
cl_temp: 1
conf_loss: 1

conf_weight: 0.9
sim_weight: 0.8
sim_loss: 0.7
# bert_lr:0.00002
# batch_size:2